### ISSUE TITLE
Automatización archivos: base de datos y labels, merge y transformación. 

### ISSUE THREAD

**Issue by jalagon** [jalagon/SpotDashMB-#2]
Eliminar el paso manual de merge y transformación. Actualmente el proceso manual toma 3 horas en el setup: al CSV de la Bestia hay que integrar data adicional desde el Dimensions del BE/AE: demográficos, atributos, breaks en fechas, etc. En la actualización: 1 hora.

**Comment by edwingrisales** [comment]
Implemented, actual process is more efficient. 1 hour aprox.
